#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "esp32 relay"
  https://create.arduino.cc/cloud/things/b38f2c2f-9581-452d-849e-f8d37cbbefa9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight aquarium_light;
  CloudLight bowllight;
  CloudLight spotlight;
  CloudLight walllight;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}

/*
  Since AquariumLight is READ_WRITE variable, onAquariumLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onAquariumLightChange()  {
  // Add your code here to act upon AquariumLight change
}

/*
  Since Spotlight is READ_WRITE variable, onSpotlightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onSpotlightChange()  {
  // Add your code here to act upon Spotlight change
}

/*
  Since Bowllight is READ_WRITE variable, onBowllightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onBowllightChange()  {
  // Add your code here to act upon Bowllight change
}

/*
  Since Walllight is READ_WRITE variable, onWalllightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onWalllightChange()  {
  // Add your code here to act upon Walllight change
}