// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5038c578-083f-4a62-99da-f58c979a4d3b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAquariumLightChange();
void onBowllightChange();
void onSpotlightChange();
void onWalllightChange();

CloudLight aquarium_light;
CloudLight bowllight;
CloudLight spotlight;
CloudLight walllight;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(aquarium_light, READWRITE, ON_CHANGE, onAquariumLightChange);
  ArduinoCloud.addProperty(bowllight, READWRITE, ON_CHANGE, onBowllightChange);
  ArduinoCloud.addProperty(spotlight, READWRITE, ON_CHANGE, onSpotlightChange);
  ArduinoCloud.addProperty(walllight, READWRITE, ON_CHANGE, onWalllightChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
